name: local_counter_app
description: Local counter app demonstrating ephemeral/local state using a StatefulWidget.
publish_to: "none"
version: 0.0.1
environment:
  sdk: ">=2.18.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

flutter:
  uses-material-design: true
